export type SeedLeadProfile = {
  id: string;
  name: string;
  email: string;
  company: string;
  companyDomain: string;
  source: string;
  timezone: string;
};

export const SEED_LEAD_PROFILES: SeedLeadProfile[] = [
  {
    id: "lead_seed",
    name: "Paul Copplestone",
    email: "paul@supabase.com",
    company: "Supabase",
    companyDomain: "supabase.com",
    source: "pricing-page",
    timezone: "America/Los_Angeles",
  },
  {
    id: "lead_05",
    name: "Amjad Masad",
    email: "amjad@replit.com",
    company: "Replit",
    companyDomain: "replit.com",
    source: "product-signup",
    timezone: "America/Los_Angeles",
  },
  {
    id: "lead_06",
    name: "Karri Saarinen",
    email: "karri@linear.app",
    company: "Linear",
    companyDomain: "linear.app",
    source: "newsletter",
    timezone: "America/Los_Angeles",
  },
  {
    id: "lead_07",
    name: "Toby Lutke",
    email: "toby@shopify.com",
    company: "Shopify",
    companyDomain: "shopify.com",
    source: "pricing-page",
    timezone: "America/Toronto",
  },
  {
    id: "lead_08",
    name: "Dylan Field",
    email: "dylan@figma.com",
    company: "Figma",
    companyDomain: "figma.com",
    source: "customer-story",
    timezone: "America/Los_Angeles",
  },
  {
    id: "lead_09",
    name: "Patrick Collison",
    email: "patrick@stripe.com",
    company: "Stripe",
    companyDomain: "stripe.com",
    source: "docs-visit",
    timezone: "America/Los_Angeles",
  },
  {
    id: "lead_11",
    name: "Jean-Denis Greze",
    email: "jdg@plaid.com",
    company: "Plaid",
    companyDomain: "plaid.com",
    source: "webinar",
    timezone: "America/New_York",
  },
  {
    id: "lead_12",
    name: "Spencer Kimball",
    email: "spencer@cockroachlabs.com",
    company: "Cockroach Labs",
    companyDomain: "cockroachlabs.com",
    source: "demo-request",
    timezone: "America/New_York",
  },
  {
    id: "lead_13",
    name: "Solomon Hykes",
    email: "solomon@dagger.io",
    company: "Dagger",
    companyDomain: "dagger.io",
    source: "github-star",
    timezone: "America/Los_Angeles",
  },
  {
    id: "lead_14",
    name: "Evan Bacon",
    email: "evan@expo.dev",
    company: "Expo",
    companyDomain: "expo.dev",
    source: "docs-visit",
    timezone: "America/Los_Angeles",
  },
  {
    id: "lead_15",
    name: "Analyse Prakash",
    email: "analyse@temporal.io",
    company: "Temporal",
    companyDomain: "temporal.io",
    source: "pricing-page",
    timezone: "America/Los_Angeles",
  },
  {
    id: "lead_16",
    name: "Simon Willison",
    email: "simon@simonwillison.net",
    company: "Datasette",
    companyDomain: "datasette.io",
    source: "newsletter",
    timezone: "America/Los_Angeles",
  },
  {
    id: "lead_17",
    name: "Sarah Drasner",
    email: "sarah@astro.build",
    company: "Astro",
    companyDomain: "astro.build",
    source: "conference",
    timezone: "America/Denver",
  },
  {
    id: "lead_18",
    name: "Peter Steinberger",
    email: "peter@steipete.me",
    company: "Polytomic",
    companyDomain: "polytomic.com",
    source: "referral",
    timezone: "Europe/Vienna",
  },
  {
    id: "lead_19",
    name: "Maël Nison",
    email: "mael@yarnpkg.com",
    company: "Yarn",
    companyDomain: "yarnpkg.com",
    source: "github-star",
    timezone: "Europe/Paris",
  },
  {
    id: "lead_20",
    name: "Jessica McKellar",
    email: "jessica@pilot.com",
    company: "Pilot",
    companyDomain: "pilot.com",
    source: "pricing-page",
    timezone: "America/Los_Angeles",
  },
  {
    id: "lead_21",
    name: "Jarred Sumner",
    email: "jarred@bun.sh",
    company: "Bun",
    companyDomain: "bun.sh",
    source: "demo-request",
    timezone: "America/Los_Angeles",
  },
];

export const SEED_LEAD_IDS = new Set(
  SEED_LEAD_PROFILES.map((profile) => profile.id),
);
